#### meta_data에 기상 데이터를 붙이기 위해 meta_data에 지역명 추가

In [1]:
import os
import pandas as pd

In [17]:
# 미리 지역 정보를 매핑한 데이터
data = [
    {"광역시": "경기도", "지역": "이천", "발전소": ["이천시 백사면A", "이천D(백사면B)"], "location_name": "이천"},
    {"광역시": "인천광역시", "지역": "인천", "발전소": ["신인천 1_2단계 주차장", "신인천 북측부지", "신인천 주차장", "신인천본관주차장", "신인천소내", "신인천전망대", "신인천해수구취수구", "인천수산정수장"], "location_name": "인천"},
    {"광역시": "강원도", "지역": "삼척", "발전소": ["삼척사택", "삼척소내_1", "삼척소내_2", "삼척소내_3", "삼척소내_4"], "location_name": "동해"},
    {"광역시": "강원도", "지역": "영월", "발전소": ["영월본부", "영월철도부지"], "location_name": "영월"},
    {"광역시": "충청북도", "지역": "음성", "발전소": ["감우리"], "location_name": "충주"},
    {"광역시": "전라북도", "지역": "익산", "발전소": ["익산 다송리"], "location_name": "전주"},
    {"광역시": "경상북도", "지역": "안동", "발전소": ["안동소내"], "location_name": "안동"},
    {"광역시": "경상남도", "지역": "하동", "발전소": ["하동공설운동장", "하동변전소", "하동보건소", "하동본부_1", "하동본부_2", "하동본부_3", "하동본부_4", "하동본부_5", "하동본부_6", "하동정수장", "하동하수처리장", "화촌주민참여형"], "location_name": "진주"},
    {"광역시": "부산", "지역": "부산", "발전소": ["부산복합자재창고", "부산본부_1", "부산본부_2", "부산수처리장", "부산신항", "부산역선상주차장", "부산운동장"], "location_name": "부산"},
    {"광역시": "제주특별자치도", "지역": "제주", "발전소": ["송당리", "남제주소내", "제주소내", "행원소수력", "용수리"], "location_name": "제주"},
    {"광역시": "제주특별자치도", "지역": "제주", "발전소": ["세화리", "신풍리", "와산리"], "location_name": "성산일출"},
    {"광역시": "제주특별자치도", "지역": "제주", "발전소": ["위미2리", "무릉리"], "location_name": "서귀포"},
]

df = pd.DataFrame(data)
df

,광역시,지역,발전소,location_name
0,경기도,이천,"[이천시 백사면A, 이천D(백사면B)]",이천
1,인천광역시,인천,"[신인천 1_2단계 주차장, 신인천 북측부지, 신인천 주차장, 신인천본관주차장, 신...",인천
2,강원도,삼척,"[삼척사택, 삼척소내_1, 삼척소내_2, 삼척소내_3, 삼척소내_4]",동해
3,강원도,영월,"[영월본부, 영월철도부지]",영월
4,충청북도,음성,[감우리],충주
5,전라북도,익산,[익산 다송리],전주
6,경상북도,안동,[안동소내],안동
7,경상남도,하동,"[하동공설운동장, 하동변전소, 하동보건소, 하동본부_1, 하동본부_2, 하동본부_3...",진주
8,부산,부산,"[부산복합자재창고, 부산본부_1, 부산본부_2, 부산수처리장, 부산신항, 부산역선상...",부산
9,제주특별자치도,제주,"[송당리, 남제주소내, 제주소내, 행원소수력, 용수리]",제주
10,제주특별자치도,제주,"[세화리, 신풍리, 와산리]",성산일출
11,제주특별자치도,제주,"[위미2리, 무릉리]",서귀포

In [18]:
data_path = '../../data/processed_data'
meta_data = pd.read_csv(os.path.join(data_path, 'meta_data.csv'))

# 먼저 발전소 이름과 location_name을 매핑한 dict 생성
mapping = {}
for _, row in df.iterrows():
    for plant in row["발전소"]:
        mapping[plant.strip()] = row["location_name"]

# meta_data의 name과 mapping 키를 비교해서 location_name 할당
meta_data["location_name"] = meta_data["name"].map(mapping)

meta_data = pd.merge(meta_data,df[['location_name','광역시']],on='location_name',how='left')#.drop_duplicates(subset=['location_name']).to_csv(os.path.join(data_path, 'location_mapping.csv'), index=False)

meta_data

,name,발전소명,구분,용량(MW),준공년도,비 고,location_name,광역시
0,감우리,감우리,자체,0.5540,2021,RPS,충주,충청북도
1,남제주소내,남제주소내태양광,자체,0.1960,2012,RPS,제주,제주특별자치도
2,무릉리,무릉리,자체,0.8090,2021,RPS,서귀포,제주특별자치도
3,부산복합자재창고,부산자재창고태양광,자체,0.1870,2012,RPS,부산,부산
4,부산수처리장,부산 수처리장 태양광,자체,0.1110,2017,RPS,부산,부산
5,부산신항,부산신항태양광,자체,0.1150,2011,RPA,부산,부산
6,부산역선상주차장,부산역 선상 주차장,자체,0.8344,2020,RPS,부산,부산
7,부산운동장,부산 운동장부지 태양광,자체,1.4000,2017,RPS,부산,부산
8,세화리,세화리,자체,0.9990,2021,RPS,성산일출,제주특별자치도
9,송당리,송당리 태양광,자체,0.9970,2019,RPS,제주,제주특별자치도
10,신인천 1_2단계 주차장,"신인천 1,2단계 주차장 태양광",자체,0.2961,2020,RPS,인천,인천광역시
11,신인천 북측부지,신인천 북측부지 태양광,자체,0.3654,2020,RPS,인천,인천광역시
12,신인천 주차장,신인천 주차장 태양광,자체,0.6030,2019,RPS,인천,인천광역시
13,신인천본관주차장,신인천 소내주차장,자체,0.2000,2021,RPS,인천,인천광역시
14,신인천소내,신인천소내태양광,자체,0.2000,2012,RPS,인천,인천광역시
15,신인천전망대,신인천 전망대 태양광,자체,1.7420,2017,RPS,인천,인천광역시
16,신인천해수구취수구,신인천해수취수로태양광,자체,0.9070,2018,RPS,인천,인천광역시
17,신풍리,신풍리,자체,0.9910,2021,RPS,성산일출,제주특별자치도
18,영월본부,영월복합태양광,자체,0.0760,2009,RPA,영월,강원도
19,영월철도부지,영월 철도부지 태양광,자체,1.1910,2018,RPS,영월,강원도
20,와산리,와산리,자체,0.8160,2022,RPS,성산일출,제주특별자치도
21,용수리,제주 용수리 태양광,자체,0.8890,2020,RPS,제주,제주특별자치도
22,위미2리,위미2리태양광,자체,0.9950,2018,RPS,서귀포,제주특별자치도
23,이천D(백사면B),백사면 B,자체,0.9990,2021,RPS,이천,경기도
24,이천시 백사면A,백사면 A,자체,1.8340,2021,RPS,이천,경기도
25,익산 다송리,익산다송리,자체,0.8920,2023,RPS,전주,전라북도
26,인천수산정수장,인천수산정수장태양광,자체,0.9980,2011,RPA,인천,인천광역시
27,하동공설운동장,하동공설운동장태양광,자체,0.3700,2011,RPA,진주,경상남도
28,하동변전소,하동변전소태양광,자체,0.0480,2011,RPA,진주,경상남도
29,하동보건소,하동군보건소태양광,자체,0.0400,2011,RPA,진주,경상남도
30,하동정수장,하동정수장태양광,자체,0.0930,2011,RPA,진주,경상남도
31,하동하수처리장,하동하수처리장태양광,자체,0.0550,2011,RPA,진주,경상남도
32,행원소수력,행원소수력태양광,자체,0.0060,2010,RPA,제주,제주특별자치도
33,화촌주민참여형,화촌 솔라팜,자체,0.9990,2021,RPS,진주,경상남도
34,부산본부_1,부산소내태양광#1,자체,0.3900,2008,FIT,부산,부산
35,부산본부_2,부산소내태양광#2,자체,0.5020,2018,RPS,부산,부산
36,삼척소내_1,삼척 소내태양광 #1,자체,0.9990,2017,RPS,동해,강원도
37,삼척소내_2,삼척 소내태양광 #2,자체,0.9900,2018,RPS,동해,강원도
38,삼척소내_3,삼척 소내태양광 #3,자체,2.0020,2018,RPS,동해,강원도
39,삼척소내_4,삼척소내#4,자체,2.5990,2019,RPS,동해,강원도
40,하동본부_1,하동화력태양광 #1,자체,0.9980,2008,FIT,진주,경상남도
41,하동본부_2,하동화력태양광 #2 (3개소),자체,1.9010,2010,RPA,진주,경상남도
42,하동본부_3,하동화력태양광 #3,자체,0.6010,2010,RPA,진주,경상남도
43,하동본부_4,하동화력태양광 #4,자체,0.9980,2017,RPS,진주,경상남도
44,하동본부_5,하동화력 태양광 #5,자체,0.9980,2018,RPS,진주,경상남도
45,하동본부_6,하동소내#6,자체,0.9980,2020,RPS,진주,경상남도

In [19]:
pd.DataFrame(meta_data['광역시'].value_counts())

         광역시
경상남도      12
제주특별자치도    9
인천광역시      8
부산         7
강원도        6
경기도        2
충청북도       1
전라북도       1

In [20]:
pd.DataFrame(meta_data['location_name'].value_counts())

      location_name
진주               12
인천                8
부산                7
제주                4
동해                4
성산일출              3
서귀포               2
영월                2
이천                2
충주                1
전주                1

In [21]:
meta_data['location_name'].unique()

array(['충주', '제주', '서귀포', '부산', '성산일출', '인천', '영월', '이천', '전주', '진주',
       '동해'], dtype=object)